name: Checkout using actions
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      #pulls our current project repo automatically
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -a
